import type {Repository} from '../types';

export type DocumentStatus='draft'|'in_review'|'approved'|'superseded'|'archived';
export type DocumentMeta={tags:string[];description:string;status:DocumentStatus;owner?:string;reviewDate?:string;ocrText?:string;ocrUpdatedAt?:number;updatedAt?:number;updatedBy?:string};
export type TagDefinition={id:string;name:string;color:string};
export type SavedView={id:string;name:string;query:string};
export type FileVersion={id:string;path:string;size:number;createdAt:number;createdByName:string;reason:string};
export type FileComment={id:string;text:string;userId?:string;userName:string;createdAt:number;editedAt?:number;resolved:boolean;resolvedAt?:number};
export type ApprovalStage={id:string;name:string;role:'admin'|'editor'};
export type ApprovalConfig={dueDays:number;stages:ApprovalStage[]};
export type FileApproval={id:string;status:'pending'|'approved'|'rejected';requestedByName:string;requestedAt:number;dueAt?:number;note?:string;reviewedByName?:string;reviewedAt?:number;response?:string;stages?:ApprovalStage[];currentStage?:number;history?:Array<{stage:string;status:string;reviewedByName:string;reviewedAt:number;response?:string}>};
export type DocumentData={metadata:Record<string,DocumentMeta>;tags:TagDefinition[];savedViews:SavedView[]};
const emptyMeta=():DocumentMeta=>({tags:[],description:'',status:'draft'});
const localKey=(scope:string)=>`folio.document-data.v1:${scope}`;
const parseLocal=(scope:string):DocumentData=>{try{return JSON.parse(localStorage.getItem(localKey(scope))||'null')||{metadata:{},tags:[],savedViews:[]};}catch{return {metadata:{},tags:[],savedViews:[]};}};
const saveLocal=(scope:string,data:DocumentData)=>localStorage.setItem(localKey(scope),JSON.stringify(data));
async function api<T>(url:string,init?:RequestInit){const response=await fetch(url,{credentials:'same-origin',...init,headers:{'content-type':'application/json',...init?.headers}}),value=await response.json().catch(()=>({}));if(!response.ok)throw new Error(value.error||'Could not save document information.');return value as T;}
export const isServerRepository=(repo:Repository|null)=>!!repo?.storageKey?.startsWith('server:');
export async function loadDocumentData(repo:Repository,department:string,scope:string):Promise<DocumentData>{if(isServerRepository(repo))return api(`/api/metadata?department=${encodeURIComponent(department)}`);return parseLocal(scope);}
export async function saveDocumentMeta(repo:Repository,department:string,scope:string,path:string,metadata:DocumentMeta){if(isServerRepository(repo)){const value=await api<{metadata:DocumentMeta}>('/api/metadata',{method:'PUT',body:JSON.stringify({department,path,metadata})});return value.metadata;}const data=parseLocal(scope);data.metadata[path]={...emptyMeta(),...metadata,updatedAt:Date.now()};saveLocal(scope,data);return data.metadata[path];}
export async function createDocumentTag(repo:Repository,department:string,scope:string,name:string,color='#71806a'){if(isServerRepository(repo))return (await api<{tags:TagDefinition[]}>('/api/tags',{method:'POST',body:JSON.stringify({department,name,color})})).tags;const data=parseLocal(scope);if(!data.tags.some(tag=>tag.name.toLowerCase()===name.trim().toLowerCase()))data.tags.push({id:crypto.randomUUID(),name:name.trim(),color});saveLocal(scope,data);return data.tags;}
export async function updateDocumentTag(repo:Repository,department:string,scope:string,id:string,name:string,color:string){if(isServerRepository(repo))return (await api<{tags:TagDefinition[]}>(`/api/tags/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({department,name,color})})).tags;const data=parseLocal(scope),tag=data.tags.find(item=>item.id===id);if(tag){tag.name=name.trim();tag.color=color;}saveLocal(scope,data);return data.tags;}
export async function deleteDocumentTag(repo:Repository,department:string,scope:string,id:string){if(isServerRepository(repo))return (await api<{tags:TagDefinition[]}>(`/api/tags/${encodeURIComponent(id)}`,{method:'DELETE',body:JSON.stringify({department})})).tags;const data=parseLocal(scope);data.tags=data.tags.filter(item=>item.id!==id);for(const meta of Object.values(data.metadata))meta.tags=(meta.tags||[]).filter(value=>value!==id);saveLocal(scope,data);return data.tags;}
export async function saveDocumentViews(repo:Repository,scope:string,views:SavedView[]){if(isServerRepository(repo))return (await api<{savedViews:SavedView[]}>('/api/saved-views',{method:'PUT',body:JSON.stringify({views})})).savedViews;const data=parseLocal(scope);data.savedViews=views;saveLocal(scope,data);return views;}
export async function loadVersions(repo:Repository,department:string,path:string):Promise<FileVersion[]>{if(!isServerRepository(repo))return [];return (await api<{versions:FileVersion[]}>(`/api/versions?department=${encodeURIComponent(department)}&path=${encodeURIComponent(path)}`)).versions;}
export async function restoreVersion(id:string){await api(`/api/versions/${encodeURIComponent(id)}/restore`,{method:'POST'});}
export async function downloadVersion(id:string,name:string){const response=await fetch(`/api/versions/${encodeURIComponent(id)}`,{credentials:'same-origin'});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||'Version unavailable.');const url=URL.createObjectURL(await response.blob()),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
export async function readVersion(id:string){const response=await fetch(`/api/versions/${encodeURIComponent(id)}`,{credentials:'same-origin'});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||'Version unavailable.');return response.blob();}
export async function deleteVersion(id:string){await api(`/api/versions/${encodeURIComponent(id)}`,{method:'DELETE'});}
export async function loadComments(repo:Repository,department:string,scope:string,path:string):Promise<FileComment[]>{if(isServerRepository(repo))return (await api<{comments:FileComment[]}>(`/api/comments?department=${encodeURIComponent(department)}&path=${encodeURIComponent(path)}`)).comments;return JSON.parse(localStorage.getItem(`${localKey(scope)}:comments:${path}`)||'[]');}
export async function addComment(repo:Repository,department:string,scope:string,path:string,text:string,userName:string){if(isServerRepository(repo))return (await api<{comment:FileComment}>('/api/comments',{method:'POST',body:JSON.stringify({department,path,text})})).comment;const key=`${localKey(scope)}:comments:${path}`,items:FileComment[]=JSON.parse(localStorage.getItem(key)||'[]'),comment={id:crypto.randomUUID(),text,userName,createdAt:Date.now(),resolved:false};items.push(comment);localStorage.setItem(key,JSON.stringify(items));return comment;}
export async function updateComment(repo:Repository,scope:string,path:string,id:string,change:{text?:string;resolved?:boolean}){if(isServerRepository(repo))return (await api<{comment:FileComment}>(`/api/comments/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(change)})).comment;const key=`${localKey(scope)}:comments:${path}`,items:FileComment[]=JSON.parse(localStorage.getItem(key)||'[]'),comment=items.find(item=>item.id===id);if(!comment)throw new Error('Comment not found.');Object.assign(comment,change,{editedAt:change.text?Date.now():comment.editedAt,resolvedAt:change.resolved?Date.now():undefined});localStorage.setItem(key,JSON.stringify(items));return comment;}
export async function deleteComment(repo:Repository,scope:string,path:string,id:string){if(isServerRepository(repo)){await api(`/api/comments/${encodeURIComponent(id)}`,{method:'DELETE'});return;}const key=`${localKey(scope)}:comments:${path}`,items:FileComment[]=JSON.parse(localStorage.getItem(key)||'[]');localStorage.setItem(key,JSON.stringify(items.filter(item=>item.id!==id)));}
export async function loadApprovals(repo:Repository,department:string,path:string):Promise<FileApproval[]>{if(!isServerRepository(repo))return [];return (await api<{approvals:FileApproval[]}>(`/api/approvals?department=${encodeURIComponent(department)}&path=${encodeURIComponent(path)}`)).approvals;}
export async function requestApproval(department:string,path:string,note=''){return (await api<{approval:FileApproval}>('/api/approvals',{method:'POST',body:JSON.stringify({department,path,note})})).approval;}
export async function reviewApproval(id:string,status:'approved'|'rejected',response=''){return (await api<{approval:FileApproval}>(`/api/approvals/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status,response})})).approval;}
export async function loadApprovalConfig(department:string){return (await api<{config:ApprovalConfig}>(`/api/approval-config?department=${encodeURIComponent(department)}`)).config;}
export async function saveApprovalConfig(department:string,config:ApprovalConfig){return (await api<{config:ApprovalConfig}>('/api/approval-config',{method:'PUT',body:JSON.stringify({department,...config})})).config;}
export async function runOcr(department:string,path:string){return (await api<{text:string;metadata:DocumentMeta}>('/api/ocr',{method:'POST',body:JSON.stringify({department,path})})).metadata;}
export async function loadTrash(){return (await api<{trash:Array<{id:string;department:string;path:string;kind:string;deletedAt:number;deletedByName:string}>}>('/api/trash')).trash;}
export async function restoreTrash(id:string){await api(`/api/trash/${encodeURIComponent(id)}/restore`,{method:'POST'});}
export async function deleteTrash(id:string){await api(`/api/trash/${encodeURIComponent(id)}`,{method:'DELETE'});}
export async function loadActivity(){return (await api<{activity:Array<{id:string;userName:string;action:string;department?:string;path?:string;at:number}>}>('/api/activity')).activity;}
export async function loadNotifications(){return (await api<{notifications:Array<{id:string;message:string;department:string;path:string;createdAt:number;read:boolean}>}>('/api/notifications')).notifications;}
export async function readNotification(id:string){await api(`/api/notifications/${encodeURIComponent(id)}`,{method:'PATCH',body:'{}'});}
