import http from 'node:http';
import {promises as fs} from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';

const port=Number(process.env.PORT||1423),dataRoot=path.resolve(process.env.FOLIO_DATA||'/data');
const ocrLanguages=/^[a-z+_-]+$/i.test(process.env.OCR_LANGUAGES||'eng')?(process.env.OCR_LANGUAGES||'eng'):'eng',ocrMaxPages=Math.min(500,Math.max(1,Number(process.env.OCR_MAX_PAGES)||50));
const versionRetention=Math.min(500,Math.max(1,Number(process.env.VERSION_RETENTION)||50)),trashRetentionDays=Math.min(3650,Math.max(1,Number(process.env.TRASH_RETENTION_DAYS)||30));
const runFile=promisify(execFile);
const statePath=path.join(dataRoot,'state.json'),filesRoot=path.join(dataRoot,'files');
const defaults=['General','Human Resources','Finance','Information Technology','Operations','Marketing','Sales','Projects'];
let state={users:[],departments:defaults,departmentStorage:{},sessions:{},activity:[],metadata:{},tags:{},savedViews:{},versions:[],trash:[],comments:[],approvals:[],approvalConfigs:{},notifications:[]};
const loginAttempts=new Map();
const loginWindowMs=15*60_000,loginLimit=8;
const publicUser=user=>({id:user.id,name:user.name,email:user.email,role:user.role,departments:user.departments,createdAt:user.createdAt});
const safeEqual=(a,b)=>{const aa=Buffer.from(a),bb=Buffer.from(b);return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb);};
const hashPassword=(password,salt)=>new Promise((resolve,reject)=>crypto.scrypt(password,salt,64,(error,key)=>error?reject(error):resolve(key.toString('hex'))));
const departmentKey=name=>Buffer.from(name).toString('base64url');
const normalizeRelative=value=>{const normalized=String(value||'').replaceAll('\\','/').split('/').filter(Boolean);if(!normalized.length||normalized.some(part=>part==='.'||part==='..'||/[\0-\x1f]/.test(part)))throw Object.assign(new Error('Invalid path.'),{status:400});return normalized.join('/');};
const atomicSave=async()=>{await fs.mkdir(dataRoot,{recursive:true});const temporary=statePath+'.tmp';await fs.writeFile(temporary,JSON.stringify(state,null,2));await fs.rename(temporary,statePath);};
const record=async(user,action,details={})=>{state.activity.unshift({id:crypto.randomUUID(),userId:user.id,userName:user.name,action,...details,at:Date.now()});state.activity=state.activity.slice(0,10000);await atomicSave();};
async function load(){await fs.mkdir(filesRoot,{recursive:true});try{state={...state,...JSON.parse(await fs.readFile(statePath,'utf8'))};}catch(error){if(error.code!=='ENOENT')throw error;}const expired=state.trash.filter(item=>item.deletedAt<Date.now()-trashRetentionDays*86400000);for(const item of expired)await fs.rm(path.join(dataRoot,'trash',item.storage),{recursive:true,force:true});state.trash=state.trash.filter(item=>!expired.includes(item));await atomicSave();}
const json=(res,status,value,headers={})=>{const body=Buffer.from(JSON.stringify(value));res.writeHead(status,{'content-type':'application/json','content-length':body.length,...headers});res.end(body);};
const fail=(res,error)=>json(res,error.status||500,{error:error.status?error.message:'The server could not complete the request.'});
const body=async(req,limit=2_000_000)=>{const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>limit)throw Object.assign(new Error('Request is too large.'),{status:413});chunks.push(chunk);}return Buffer.concat(chunks);};
const jsonBody=async req=>{try{return JSON.parse((await body(req)).toString('utf8')||'{}');}catch{throw Object.assign(new Error('Invalid request.'),{status:400});}};
const cookies=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(item=>item.trim().split('=').map(decodeURIComponent)).filter(item=>item.length===2));
const sessionUser=req=>{const session=state.sessions[cookies(req).folio_session];if(!session||session.expiresAt<Date.now())return;return state.users.find(user=>user.id===session.userId);};
const requireUser=req=>{const user=sessionUser(req);if(!user)throw Object.assign(new Error('Sign in to continue.'),{status:401});return user;};
const requireAdmin=user=>{if(user.role!=='admin')throw Object.assign(new Error('Administrator access is required.'),{status:403});};
const requireEdit=user=>{if(user.role==='reader')throw Object.assign(new Error('This account has read-only access.'),{status:403});};
const canAccess=(user,department)=>department==='Personal'||user.role==='admin'||user.departments.includes(department);
const workspaceRoot=(user,department)=>{if(department==='Personal')return path.join(filesRoot,'personal',user.id);if(!state.departments.includes(department)||!canAccess(user,department))throw Object.assign(new Error('You do not have access to this department.'),{status:403});return path.join(filesRoot,'departments',state.departmentStorage[department]||departmentKey(department));};
const workspaceId=(user,department)=>department==='Personal'?`personal:${user.id}`:`department:${department}`;
const resolvedEntry=(root,relative)=>{const resolved=path.resolve(root,normalizeRelative(relative));if(resolved!==root&&!resolved.startsWith(root+path.sep))throw Object.assign(new Error('Invalid path.'),{status:400});return resolved;};
async function listEntries(root){const result=[];async function walk(directory,prefix=''){let items=[];try{items=await fs.readdir(directory,{withFileTypes:true});}catch(error){if(error.code==='ENOENT')return;throw error;}for(const item of items){if(item.name.startsWith('.'))continue;const relative=prefix?`${prefix}/${item.name}`:item.name,absolute=path.join(directory,item.name);if(item.isDirectory()){result.push({path:relative,name:item.name,kind:'folder',size:0,modified:(await fs.stat(absolute)).mtimeMs});await walk(absolute,relative);}else if(item.isFile()){const stat=await fs.stat(absolute);result.push({path:relative,name:item.name,kind:'file',size:stat.size,modified:stat.mtimeMs});}}}await walk(root);return result;}
async function copyEntry(from,to){const stat=await fs.stat(from);if(stat.isDirectory()){await fs.mkdir(to,{recursive:false});for(const name of await fs.readdir(from))await copyEntry(path.join(from,name),path.join(to,name));}else await fs.copyFile(from,to,fs.constants.COPYFILE_EXCL);}
async function moveEntry(from,to){
  try{return await fs.rename(from,to);}
  catch(error){
    // Windows can temporarily deny renaming a directory while a preview or file
    // stream still has a handle open inside it. Preserve rename semantics with a
    // copy/remove fallback for those platform errors (and cross-device moves).
    if(!['EPERM','EACCES','EXDEV'].includes(error.code))throw error;
  }
  try{
    await copyEntry(from,to);
    await fs.rm(from,{recursive:true,force:false,maxRetries:8,retryDelay:125});
  }catch(error){
    await fs.rm(to,{recursive:true,force:true,maxRetries:3,retryDelay:100}).catch(()=>{});
    throw error;
  }
}
async function snapshotVersion(user,department,relative,absolute,reason='edited'){const stat=await fs.stat(absolute).catch(()=>null);if(!stat?.isFile())return;const id=crypto.randomUUID(),versionPath=path.join(dataRoot,'versions',id),workspace=workspaceId(user,department);await fs.mkdir(path.dirname(versionPath),{recursive:true});await fs.copyFile(absolute,versionPath);state.versions.unshift({id,workspace,department,path:relative,size:stat.size,createdAt:Date.now(),createdBy:user.id,createdByName:user.name,reason,storage:id});const old=state.versions.filter(item=>item.workspace===workspace&&item.path===relative).slice(versionRetention);for(const item of old)await fs.rm(path.join(dataRoot,'versions',item.storage),{force:true});if(old.length)state.versions=state.versions.filter(item=>!old.includes(item));}
const sessionCookie=(id,remember)=>`folio_session=${encodeURIComponent(id)}; Path=/; HttpOnly; SameSite=Strict${remember?'; Max-Age=2592000':''}`;

async function handle(req,res){
  const url=new URL(req.url,'http://localhost'),route=url.pathname;
  if(route==='/api/health')return json(res,200,{ok:true});
  if(route==='/api/status'&&req.method==='GET')return json(res,200,{needsSetup:state.users.length===0,authenticated:!!sessionUser(req)});
  if(route==='/api/setup'&&req.method==='POST'){
    if(state.users.length)throw Object.assign(new Error('Folio is already configured.'),{status:409});const input=await jsonBody(req);
    if(!input.name?.trim()||!/^\S+@\S+\.\S+$/.test(input.email||'')||String(input.password||'').length<8)throw Object.assign(new Error('Name, a valid email, and an 8-character password are required.'),{status:400});
    const salt=crypto.randomBytes(16).toString('hex'),user={id:crypto.randomUUID(),name:input.name.trim(),email:input.email.trim().toLowerCase(),role:'admin',departments:[],salt,passwordHash:await hashPassword(input.password,salt),createdAt:Date.now()};state.users.push(user);const id=crypto.randomBytes(32).toString('base64url');state.sessions[id]={userId:user.id,expiresAt:Date.now()+30*86400000};await atomicSave();return json(res,201,{user:publicUser(user),users:[publicUser(user)],departments:state.departments},{'set-cookie':sessionCookie(id,true)});
  }
  if(route==='/api/login'&&req.method==='POST'){
    const input=await jsonBody(req),email=String(input.email||'').trim().toLowerCase(),attempt=loginAttempts.get(email);if(attempt&&attempt.resetAt>Date.now()&&attempt.count>=loginLimit)throw Object.assign(new Error('Too many sign-in attempts. Try again in 15 minutes.'),{status:429});const user=state.users.find(item=>item.email===email);if(!user||!safeEqual(await hashPassword(String(input.password||''),user.salt),user.passwordHash)){const current=attempt?.resetAt>Date.now()?attempt:{count:0,resetAt:Date.now()+loginWindowMs};current.count++;loginAttempts.set(email,current);throw Object.assign(new Error('The email or password is incorrect.'),{status:401});}loginAttempts.delete(email);
    const id=crypto.randomBytes(32).toString('base64url');state.sessions[id]={userId:user.id,expiresAt:Date.now()+(input.remember?30*86400000:12*3600000)};await atomicSave();return json(res,200,{user:publicUser(user)},{'set-cookie':sessionCookie(id,!!input.remember)});
  }
  if(route==='/api/logout'&&req.method==='POST'){const id=cookies(req).folio_session;if(id)delete state.sessions[id];await atomicSave();return json(res,200,{ok:true},{'set-cookie':'folio_session=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0'});}
  const user=requireUser(req);
  if(route==='/api/bootstrap'&&req.method==='GET')return json(res,200,{user:publicUser(user),users:user.role==='admin'?state.users.map(publicUser):[publicUser(user)],departments:state.departments});
  if(route==='/api/users'&&req.method==='POST'){requireAdmin(user);const input=await jsonBody(req);if(state.users.some(item=>item.email===String(input.email).trim().toLowerCase()))throw Object.assign(new Error('That email is already in use.'),{status:409});if(String(input.password||'').length<8)throw Object.assign(new Error('Use at least 8 characters.'),{status:400});const salt=crypto.randomBytes(16).toString('hex'),created={id:crypto.randomUUID(),name:String(input.name||'').trim(),email:String(input.email||'').trim().toLowerCase(),role:input.role,departments:[...new Set(input.departments||[])].filter(item=>state.departments.includes(item)),salt,passwordHash:await hashPassword(input.password,salt),createdAt:Date.now()};state.users.push(created);await record(user,'user.created',{targetUserId:created.id});return json(res,201,{user:publicUser(created)});}
  const userMatch=route.match(/^\/api\/users\/([^/]+)$/);if(userMatch){requireAdmin(user);const target=state.users.find(item=>item.id===decodeURIComponent(userMatch[1]));if(!target)throw Object.assign(new Error('User not found.'),{status:404});if(req.method==='PATCH'){const input=await jsonBody(req);if(input.email&&state.users.some(item=>item.id!==target.id&&item.email===String(input.email).trim().toLowerCase()))throw Object.assign(new Error('That email is already in use.'),{status:409});if(input.name)target.name=String(input.name).trim();if(input.email)target.email=String(input.email).trim().toLowerCase();if(['admin','editor','reader'].includes(input.role))target.role=input.role;if(Array.isArray(input.departments))target.departments=[...new Set(input.departments)].filter(item=>state.departments.includes(item));if(input.password){if(String(input.password).length<8)throw Object.assign(new Error('Use at least 8 characters.'),{status:400});target.salt=crypto.randomBytes(16).toString('hex');target.passwordHash=await hashPassword(input.password,target.salt);}await record(user,'user.updated',{targetUserId:target.id});return json(res,200,{user:publicUser(target)});}if(req.method==='DELETE'){if(target.id===user.id)throw Object.assign(new Error('You cannot remove your own account.'),{status:409});if(target.role==='admin'&&state.users.filter(item=>item.role==='admin').length===1)throw Object.assign(new Error('Keep at least one administrator.'),{status:409});state.users=state.users.filter(item=>item.id!==target.id);for(const [id,session] of Object.entries(state.sessions))if(session.userId===target.id)delete state.sessions[id];await record(user,'user.deleted',{targetUserId:target.id});return json(res,200,{ok:true});}}
  if(route==='/api/departments'&&req.method==='POST'){requireAdmin(user);const input=await jsonBody(req),name=String(input.name||'').trim();if(!name||name==='Personal'||state.departments.some(item=>item.toLowerCase()===name.toLowerCase()))throw Object.assign(new Error('Enter a unique department name.'),{status:409});state.departmentStorage[name]=crypto.randomUUID();state.departments.push(name);await record(user,'department.created',{department:name});return json(res,201,{departments:state.departments});}
  const departmentMatch=route.match(/^\/api\/departments\/([^/]+)$/);if(departmentMatch){requireAdmin(user);const previous=decodeURIComponent(departmentMatch[1]);if(req.method==='PATCH'){const input=await jsonBody(req),next=String(input.name||'').trim();if(!state.departments.includes(previous)||!next||state.departments.some(item=>item!==previous&&item.toLowerCase()===next.toLowerCase()))throw Object.assign(new Error('Enter a unique department name.'),{status:409});if(next==='Personal')throw Object.assign(new Error('Enter a unique department name.'),{status:409});
    if(next===previous)return json(res,200,{departments:state.departments});
    // Keep storage paths stable while Windows previews or editors have files open.
    state.departmentStorage[next]=state.departmentStorage[previous]||departmentKey(previous);
    delete state.departmentStorage[previous];
    const oldWorkspace='department:'+previous,newWorkspace='department:'+next;
    for(const collection of [state.metadata,state.tags]){
      if(Object.hasOwn(collection,oldWorkspace)){collection[newWorkspace]=collection[oldWorkspace];delete collection[oldWorkspace];}
    }
    if(Object.hasOwn(state.approvalConfigs,previous)){state.approvalConfigs[next]=state.approvalConfigs[previous];delete state.approvalConfigs[previous];}
    for(const collection of [state.versions,state.trash,state.comments,state.approvals])for(const item of collection){if(item.workspace===oldWorkspace){item.workspace=newWorkspace;item.department=next;}}
    for(const item of state.notifications)if(item.department===previous)item.department=next;
    state.departments=state.departments.map(item=>item===previous?next:item);for(const account of state.users)account.departments=account.departments.map(item=>item===previous?next:item);await record(user,'department.renamed',{department:previous,next});return json(res,200,{departments:state.departments});}if(req.method==='DELETE'){if(state.departments.length<=1)throw Object.assign(new Error('Keep at least one department.'),{status:409});state.departments=state.departments.filter(item=>item!==previous);for(const account of state.users)account.departments=account.departments.filter(item=>item!==previous);await record(user,'department.removed',{department:previous});return json(res,200,{departments:state.departments});}}
  if(route==='/api/files'&&req.method==='GET'){const department=url.searchParams.get('department')||'General',root=workspaceRoot(user,department);await fs.mkdir(root,{recursive:true});return json(res,200,{entries:await listEntries(root)});}
  if(route==='/api/files/content'){
    const department=url.searchParams.get('department')||'General',relative=normalizeRelative(url.searchParams.get('path')),root=workspaceRoot(user,department),absolute=resolvedEntry(root,relative);
    if(req.method==='GET'){const stat=await fs.stat(absolute).catch(()=>null);if(!stat?.isFile())throw Object.assign(new Error('File not found.'),{status:404});res.writeHead(200,{'content-type':'application/octet-stream','content-length':stat.size,'cache-control':'no-store'});return fs.open(absolute,'r').then(file=>{file.createReadStream().pipe(res).on('close',()=>file.close());});}
    if(req.method==='PUT'){requireEdit(user);await fs.mkdir(path.dirname(absolute),{recursive:true});const replace=url.searchParams.get('replace')==='1',exists=await fs.stat(absolute).then(()=>true).catch(()=>false);if(!replace&&exists)throw Object.assign(new Error('An item with this name already exists.'),{status:409});if(replace&&exists)await snapshotVersion(user,department,relative,absolute);await fs.writeFile(absolute,await body(req,250_000_000));await record(user,replace?'file.edited':'file.created',{department,path:relative});return json(res,201,{ok:true});}
  }
  if(route==='/api/folders'&&req.method==='POST'){requireEdit(user);const input=await jsonBody(req),department=input.department||'General',root=workspaceRoot(user,department),relative=normalizeRelative(input.path),absolute=resolvedEntry(root,relative);await fs.mkdir(root,{recursive:true});try{await fs.mkdir(absolute,{recursive:false});}catch(error){if(error.code==='EEXIST')throw Object.assign(new Error('That folder already exists.'),{status:409});throw error;}await record(user,'folder.created',{department,path:relative});return json(res,201,{ok:true});}
  if(route==='/api/files/move'&&req.method==='POST'){requireEdit(user);const input=await jsonBody(req),fromDepartment=input.fromDepartment||'General',toDepartment=input.toDepartment||fromDepartment,fromRoot=workspaceRoot(user,fromDepartment),toRoot=workspaceRoot(user,toDepartment),from=normalizeRelative(input.from),to=normalizeRelative(input.to),source=resolvedEntry(fromRoot,from),destination=resolvedEntry(toRoot,to);await fs.stat(source).catch(error=>{if(error.code==='ENOENT')throw Object.assign(new Error('This item is no longer in this workspace. Refresh the folder list and try again.'),{status:404});throw error;});if(await fs.stat(destination).then(()=>true).catch(()=>false))throw Object.assign(new Error('An item with this name already exists.'),{status:409});await fs.mkdir(path.dirname(destination),{recursive:true});if(input.copy)await copyEntry(source,destination);else await moveEntry(source,destination);const fromWorkspace=workspaceId(user,fromDepartment),toWorkspace=workspaceId(user,toDepartment),fromMetadata=state.metadata[fromWorkspace]||{},toMetadata=state.metadata[toWorkspace]||{};for(const [key,value] of Object.entries(fromMetadata)){if(key===from||key.startsWith(from+'/')){const next=to+key.slice(from.length);toMetadata[next]=structuredClone(value);if(!input.copy)delete fromMetadata[key];}}state.metadata[fromWorkspace]=fromMetadata;state.metadata[toWorkspace]=toMetadata;await record(user,input.copy?'entry.copied':'entry.moved',{department:fromDepartment,path:from,toDepartment,to});return json(res,200,{ok:true});}
  if(route==='/api/files'&&req.method==='DELETE'){requireEdit(user);const input=await jsonBody(req),department=input.department||'General',root=workspaceRoot(user,department),relative=normalizeRelative(input.path),absolute=resolvedEntry(root,relative),stat=await fs.stat(absolute).catch(()=>null);if(!stat)throw Object.assign(new Error('Item not found.'),{status:404});const id=crypto.randomUUID(),trashPath=path.join(dataRoot,'trash',id);await fs.mkdir(path.dirname(trashPath),{recursive:true});await fs.rename(absolute,trashPath);const workspace=workspaceId(user,department),metadata={};for(const [key,value] of Object.entries(state.metadata[workspace]||{}))if(key===relative||key.startsWith(relative+'/')){metadata[key]=value;delete state.metadata[workspace][key];}state.trash.unshift({id,workspace,department,path:relative,kind:stat.isDirectory()?'folder':'file',deletedAt:Date.now(),deletedBy:user.id,deletedByName:user.name,storage:id,metadata});await record(user,'entry.trashed',{department,path:relative});return json(res,200,{ok:true});}
  if(route==='/api/metadata'&&req.method==='GET'){const department=url.searchParams.get('department')||'General';workspaceRoot(user,department);const workspace=workspaceId(user,department);return json(res,200,{metadata:state.metadata[workspace]||{},tags:state.tags[workspace]||[],savedViews:state.savedViews[user.id]||[]});}
  if(route==='/api/metadata'&&req.method==='PUT'){requireEdit(user);const input=await jsonBody(req),department=input.department||'General',relative=normalizeRelative(input.path);workspaceRoot(user,department);const workspace=workspaceId(user,department),current=state.metadata[workspace]||{};current[relative]={...(current[relative]||{}),...input.metadata,updatedAt:Date.now(),updatedBy:user.id};state.metadata[workspace]=current;await record(user,'metadata.updated',{department,path:relative});return json(res,200,{metadata:current[relative]});}
  if(route==='/api/tags'&&req.method==='POST'){requireEdit(user);const input=await jsonBody(req),department=input.department||'General',name=String(input.name||'').trim();workspaceRoot(user,department);if(!name)throw Object.assign(new Error('Enter a tag name.'),{status:400});const workspace=workspaceId(user,department),tags=state.tags[workspace]||[];if(!tags.some(tag=>tag.name.toLowerCase()===name.toLowerCase()))tags.push({id:crypto.randomUUID(),name,color:String(input.color||'#71806a')});state.tags[workspace]=tags;await atomicSave();return json(res,201,{tags});}
  const tagMatch=route.match(/^\/api\/tags\/([^/]+)$/);if(tagMatch){requireEdit(user);const input=await jsonBody(req),department=input.department||'General',workspace=workspaceId(user,department);workspaceRoot(user,department);const tags=state.tags[workspace]||[],tag=tags.find(item=>item.id===tagMatch[1]);if(!tag)throw Object.assign(new Error('Tag not found.'),{status:404});if(req.method==='PATCH'){const name=String(input.name||tag.name).trim();if(!name)throw Object.assign(new Error('Enter a tag name.'),{status:400});const mergeTarget=tags.find(item=>item.id!==tag.id&&item.name.toLowerCase()===name.toLowerCase());if(mergeTarget){for(const meta of Object.values(state.metadata[workspace]||{}))if((meta.tags||[]).includes(tag.id))meta.tags=[...new Set(meta.tags.map(id=>id===tag.id?mergeTarget.id:id))];state.tags[workspace]=tags.filter(item=>item.id!==tag.id);await record(user,'tag.merged',{department,tagId:tag.id,targetTagId:mergeTarget.id});return json(res,200,{tags:state.tags[workspace]});}tag.name=name;tag.color=String(input.color||tag.color);await record(user,'tag.updated',{department,tagId:tag.id});return json(res,200,{tags});}if(req.method==='DELETE'){state.tags[workspace]=tags.filter(item=>item.id!==tag.id);for(const meta of Object.values(state.metadata[workspace]||{}))meta.tags=(meta.tags||[]).filter(id=>id!==tag.id);await record(user,'tag.deleted',{department,tagId:tag.id});return json(res,200,{tags:state.tags[workspace]});}}
  if(route==='/api/saved-views'&&req.method==='PUT'){const input=await jsonBody(req),views=Array.isArray(input.views)?input.views.slice(0,50):[];state.savedViews[user.id]=views;await atomicSave();return json(res,200,{savedViews:views});}
  if(route==='/api/versions'&&req.method==='GET'){const department=url.searchParams.get('department')||'General',relative=normalizeRelative(url.searchParams.get('path'));workspaceRoot(user,department);return json(res,200,{versions:state.versions.filter(item=>item.workspace===workspaceId(user,department)&&item.path===relative)});}
  const restoreVersion=route.match(/^\/api\/versions\/([^/]+)\/restore$/);if(restoreVersion&&req.method==='POST'){requireEdit(user);const version=state.versions.find(item=>item.id===restoreVersion[1]);if(!version)throw Object.assign(new Error('Version not found.'),{status:404});const root=workspaceRoot(user,version.department),absolute=resolvedEntry(root,version.path);await snapshotVersion(user,version.department,version.path,absolute,'restored');await fs.copyFile(path.join(dataRoot,'versions',version.storage),absolute);await record(user,'version.restored',{department:version.department,path:version.path,versionId:version.id});return json(res,200,{ok:true});}
  const versionMatch=route.match(/^\/api\/versions\/([^/]+)$/);if(versionMatch){const version=state.versions.find(item=>item.id===versionMatch[1]);if(!version)throw Object.assign(new Error('Version not found.'),{status:404});workspaceRoot(user,version.department);if(req.method==='GET'){const absolute=path.join(dataRoot,'versions',version.storage),stat=await fs.stat(absolute);res.writeHead(200,{'content-type':'application/octet-stream','content-length':stat.size,'content-disposition':`attachment; filename="${path.basename(version.path).replaceAll('"','')}"`});return fs.open(absolute,'r').then(file=>{file.createReadStream().pipe(res).on('close',()=>file.close());});}if(req.method==='DELETE'){requireAdmin(user);await fs.rm(path.join(dataRoot,'versions',version.storage),{force:true});state.versions=state.versions.filter(item=>item.id!==version.id);await record(user,'version.deleted',{department:version.department,path:version.path,versionId:version.id});return json(res,200,{ok:true});}}
  if(route==='/api/trash'&&req.method==='GET'){return json(res,200,{trash:state.trash.filter(item=>canAccess(user,item.department)&&item.workspace===workspaceId(user,item.department))});}
  const restoreTrash=route.match(/^\/api\/trash\/([^/]+)\/restore$/);if(restoreTrash&&req.method==='POST'){requireEdit(user);const item=state.trash.find(value=>value.id===restoreTrash[1]);if(!item)throw Object.assign(new Error('Deleted item not found.'),{status:404});const root=workspaceRoot(user,item.department),destination=resolvedEntry(root,item.path);if(await fs.stat(destination).then(()=>true).catch(()=>false))throw Object.assign(new Error('An item with this name already exists.'),{status:409});await fs.mkdir(path.dirname(destination),{recursive:true});await fs.rename(path.join(dataRoot,'trash',item.storage),destination);state.metadata[item.workspace]={...(state.metadata[item.workspace]||{}),...item.metadata};state.trash=state.trash.filter(value=>value.id!==item.id);await record(user,'entry.restored',{department:item.department,path:item.path});return json(res,200,{ok:true});}
  const trashMatch=route.match(/^\/api\/trash\/([^/]+)$/);if(trashMatch&&req.method==='DELETE'){requireAdmin(user);const item=state.trash.find(value=>value.id===trashMatch[1]);if(!item)throw Object.assign(new Error('Deleted item not found.'),{status:404});workspaceRoot(user,item.department);await fs.rm(path.join(dataRoot,'trash',item.storage),{recursive:true,force:true});state.trash=state.trash.filter(value=>value.id!==item.id);await record(user,'entry.deleted_permanently',{department:item.department,path:item.path});return json(res,200,{ok:true});}
  if(route==='/api/comments'&&req.method==='GET'){const department=url.searchParams.get('department')||'General',relative=normalizeRelative(url.searchParams.get('path'));workspaceRoot(user,department);return json(res,200,{comments:state.comments.filter(item=>item.workspace===workspaceId(user,department)&&item.path===relative)});}
  if(route==='/api/comments'&&req.method==='POST'){const input=await jsonBody(req),department=input.department||'General',relative=normalizeRelative(input.path),text=String(input.text||'').trim();workspaceRoot(user,department);if(!text)throw Object.assign(new Error('Enter a comment.'),{status:400});const comment={id:crypto.randomUUID(),workspace:workspaceId(user,department),department,path:relative,text,userId:user.id,userName:user.name,createdAt:Date.now(),resolved:false};state.comments.push(comment);const lower=text.toLowerCase();for(const target of state.users){if(target.id===user.id||!canAccess(target,department)||(department==='Personal'&&target.id!==user.id))continue;const handles=[target.name, target.email, target.email.split('@')[0]].map(value=>'@'+value.toLowerCase());if(handles.some(handle=>lower.includes(handle)))state.notifications.unshift({id:crypto.randomUUID(),userId:target.id,type:'mention',message:`${user.name} mentioned you in ${relative}`,department,path:relative,createdAt:Date.now(),read:false});}await record(user,'comment.added',{department,path:relative});return json(res,201,{comment});}
  const commentMatch=route.match(/^\/api\/comments\/([^/]+)$/);if(commentMatch){const comment=state.comments.find(item=>item.id===commentMatch[1]);if(!comment)throw Object.assign(new Error('Comment not found.'),{status:404});workspaceRoot(user,comment.department);if(comment.userId!==user.id&&user.role!=='admin')throw Object.assign(new Error('Only the author or an administrator can change this comment.'),{status:403});if(req.method==='PATCH'){const input=await jsonBody(req);if(typeof input.text==='string'){const text=input.text.trim();if(!text)throw Object.assign(new Error('A comment cannot be empty.'),{status:400});comment.text=text;comment.editedAt=Date.now();}if(typeof input.resolved==='boolean'){comment.resolved=input.resolved;comment.resolvedAt=input.resolved?Date.now():undefined;comment.resolvedBy=input.resolved?user.id:undefined;}await record(user,comment.resolved?'comment.resolved':'comment.updated',{department:comment.department,path:comment.path});return json(res,200,{comment});}if(req.method==='DELETE'){state.comments=state.comments.filter(item=>item.id!==comment.id);await record(user,'comment.deleted',{department:comment.department,path:comment.path});return json(res,200,{ok:true});}}
  if(route==='/api/notifications'&&req.method==='GET')return json(res,200,{notifications:state.notifications.filter(item=>item.userId===user.id).slice(0,100)});
  const notificationMatch=route.match(/^\/api\/notifications\/([^/]+)$/);if(notificationMatch&&req.method==='PATCH'){const notification=state.notifications.find(item=>item.id===notificationMatch[1]&&item.userId===user.id);if(!notification)throw Object.assign(new Error('Notification not found.'),{status:404});notification.read=true;await atomicSave();return json(res,200,{notification});}
  if(route==='/api/approval-config'&&req.method==='GET'){const department=url.searchParams.get('department')||'General';workspaceRoot(user,department);return json(res,200,{config:state.approvalConfigs[department]||{dueDays:7,stages:[{id:'default',name:'Administrator approval',role:'admin'}]}});}
  if(route==='/api/approval-config'&&req.method==='PUT'){requireAdmin(user);const input=await jsonBody(req),department=input.department||'General';workspaceRoot(user,department);const dueDays=Math.min(365,Math.max(1,Number(input.dueDays)||7)),stages=(Array.isArray(input.stages)?input.stages:[]).slice(0,10).map(stage=>({id:String(stage.id||crypto.randomUUID()),name:String(stage.name||'Approval').trim().slice(0,80),role:['admin','editor'].includes(stage.role)?stage.role:'admin'})).filter(stage=>stage.name);if(!stages.length)throw Object.assign(new Error('Add at least one approval stage.'),{status:400});state.approvalConfigs[department]={dueDays,stages};await record(user,'approval.configuration_updated',{department});return json(res,200,{config:state.approvalConfigs[department]});}
  if(route==='/api/approvals'&&req.method==='GET'){const department=url.searchParams.get('department')||'General',relative=normalizeRelative(url.searchParams.get('path'));workspaceRoot(user,department);return json(res,200,{approvals:state.approvals.filter(item=>item.workspace===workspaceId(user,department)&&item.path===relative)});}
  if(route==='/api/approvals'&&req.method==='POST'){requireEdit(user);const input=await jsonBody(req),department=input.department||'General',relative=normalizeRelative(input.path);workspaceRoot(user,department);const workspace=workspaceId(user,department),config=state.approvalConfigs[department]||{dueDays:7,stages:[{id:'default',name:'Administrator approval',role:'admin'}]},approval={id:crypto.randomUUID(),workspace,department,path:relative,status:'pending',requestedBy:user.id,requestedByName:user.name,requestedAt:Date.now(),dueAt:Date.now()+config.dueDays*86400000,note:String(input.note||''),stages:structuredClone(config.stages),currentStage:0,history:[]};state.approvals.push(approval);state.metadata[workspace] ||= {};state.metadata[workspace][relative]={tags:[],description:'',...(state.metadata[workspace][relative]||{}),status:'in_review',updatedAt:Date.now(),updatedBy:user.id};await record(user,'approval.requested',{department,path:relative});return json(res,201,{approval});}
  const approvalMatch=route.match(/^\/api\/approvals\/([^/]+)$/);if(approvalMatch&&req.method==='PATCH'){const approval=state.approvals.find(item=>item.id===approvalMatch[1]);if(!approval)throw Object.assign(new Error('Approval request not found.'),{status:404});workspaceRoot(user,approval.department);const stage=(approval.stages||[{name:'Administrator approval',role:'admin'}])[approval.currentStage||0];if(user.role!=='admin'&&user.role!==stage.role)throw Object.assign(new Error(`This stage requires an ${stage.role}.`),{status:403});const input=await jsonBody(req);if(!['approved','rejected'].includes(input.status))throw Object.assign(new Error('Choose approve or reject.'),{status:400});approval.history ||= [];approval.history.push({stage:stage.name,status:input.status,reviewedBy:user.id,reviewedByName:user.name,reviewedAt:Date.now(),response:String(input.response||'')});if(input.status==='approved'&&(approval.currentStage||0)<(approval.stages?.length||1)-1){approval.currentStage=(approval.currentStage||0)+1;approval.status='pending';}else{approval.status=input.status;approval.reviewedBy=user.id;approval.reviewedByName=user.name;approval.reviewedAt=Date.now();approval.response=String(input.response||'');}state.metadata[approval.workspace] ||= {};state.metadata[approval.workspace][approval.path]={tags:[],description:'',...(state.metadata[approval.workspace][approval.path]||{}),status:approval.status==='approved'?'approved':approval.status==='rejected'?'draft':'in_review',updatedAt:Date.now(),updatedBy:user.id};await record(user,`approval.${input.status}`,{department:approval.department,path:approval.path,stage:stage.name});return json(res,200,{approval});}
  if(route==='/api/ocr'&&req.method==='POST'){requireEdit(user);const input=await jsonBody(req),department=input.department||'General',relative=normalizeRelative(input.path),root=workspaceRoot(user,department),absolute=resolvedEntry(root,relative),extension=path.extname(relative).toLowerCase();if(!['.pdf','.png','.jpg','.jpeg','.tif','.tiff','.bmp','.webp'].includes(extension))throw Object.assign(new Error('OCR supports PDF and image files.'),{status:400});const temporary=await fs.mkdtemp(path.join(dataRoot,'ocr-'));try{let images=[absolute];if(extension==='.pdf'){const prefix=path.join(temporary,'page');await runFile('pdftoppm',['-f','1','-l',String(ocrMaxPages),'-png','-r','150',absolute,prefix],{maxBuffer:10_000_000});images=(await fs.readdir(temporary)).filter(name=>name.endsWith('.png')).sort().map(name=>path.join(temporary,name));}const pages=[];for(const image of images){const result=await runFile('tesseract',[image,'stdout','-l',ocrLanguages],{maxBuffer:20_000_000});pages.push(result.stdout);}const text=pages.join('\n\n').trim(),workspace=workspaceId(user,department);state.metadata[workspace] ||= {};state.metadata[workspace][relative]={tags:[],description:'',status:'draft',...(state.metadata[workspace][relative]||{}),ocrText:text,ocrUpdatedAt:Date.now(),ocrLanguages,updatedAt:Date.now(),updatedBy:user.id};await record(user,'ocr.completed',{department,path:relative,pages:images.length,languages:ocrLanguages});return json(res,200,{text,metadata:state.metadata[workspace][relative]});}finally{await fs.rm(temporary,{recursive:true,force:true});}}
  if(route==='/api/activity'&&req.method==='GET'){const visible=state.activity.filter(item=>item.department?canAccess(user,item.department):user.role==='admin'||item.userId===user.id);return json(res,200,{activity:visible.slice(0,500)});}
  throw Object.assign(new Error('Not found.'),{status:404});
}

await load();
const server=http.createServer((req,res)=>handle(req,res).catch(error=>{console.error(error);fail(res,error);}));
server.listen(port,'0.0.0.0',()=>console.log(`Folio API listening on ${port}`));
