import {useEffect,useState} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {loadApprovalConfig,saveApprovalConfig,type ApprovalConfig} from '../services/documentData';
export default function ApprovalSettings({departments}:{departments:string[]}){
  const [department,setDepartment]=useState(departments[0]||''),[config,setConfig]=useState<ApprovalConfig>({dueDays:7,stages:[]}),[message,setMessage]=useState('');
  useEffect(()=>{if(department)loadApprovalConfig(department).then(setConfig).catch(e=>setMessage((e as Error).message));},[department]);
  function update(index:number,field:'name'|'role',value:string){setConfig(current=>({...current,stages:current.stages.map((stage,i)=>i===index?{...stage,[field]:value}:stage)}));}
  return <div className="settings-section"><div className="section-heading"><div><h3>Approval workflow</h3><p>Choose reviewer stages and a deadline for each department.</p></div></div><label>Department<select value={department} onChange={e=>setDepartment(e.target.value)}>{departments.map(item=><option key={item}>{item}</option>)}</select></label><label>Days to complete<input type="number" min="1" max="365" value={config.dueDays} onChange={e=>setConfig(v=>({...v,dueDays:Number(e.target.value)}))}/></label><div className="approval-config-list">{config.stages.map((stage,index)=><div key={stage.id}><span>{index+1}</span><input aria-label={`Stage ${index+1} name`} value={stage.name} onChange={e=>update(index,'name',e.target.value)}/><select aria-label={`Stage ${index+1} reviewer role`} value={stage.role} onChange={e=>update(index,'role',e.target.value)}><option value="admin">Administrator</option><option value="editor">Editor</option></select><button className="icon-button danger" disabled={config.stages.length===1} onClick={()=>setConfig(v=>({...v,stages:v.stages.filter((_,i)=>i!==index)}))}><Trash2 size={14}/></button></div>)}</div><button className="secondary-button" onClick={()=>setConfig(v=>({...v,stages:[...v.stages,{id:crypto.randomUUID(),name:`Approval ${v.stages.length+1}`,role:'admin'}]}))}><Plus size={13}/>Add stage</button><button className="primary-button" disabled={!department||!config.stages.length} onClick={async()=>{try{setConfig(await saveApprovalConfig(department,config));setMessage('Approval workflow saved.');}catch(e){setMessage((e as Error).message);}}}>Save workflow</button>{message&&<p className="muted-note">{message}</p>}</div>;
}
