import {useEffect,useState} from 'react';
import {Check,Clock3,Columns2,Download,History,MessageSquare,Pencil,Plus,RotateCcw,ScanText,Send,Tag,Trash2,X} from 'lucide-react';
import type {Entry,Repository} from '../types';
import {addComment,createDocumentTag,deleteComment,deleteDocumentTag,deleteVersion,downloadVersion,isServerRepository,loadApprovals,loadComments,loadVersions,readVersion,requestApproval,restoreVersion,reviewApproval,runOcr,saveDocumentMeta,updateComment,updateDocumentTag,type DocumentMeta,type FileApproval,type FileComment,type FileVersion,type TagDefinition} from '../services/documentData';

type Props={entry:Entry;repo:Repository;department:string;scope:string;meta:DocumentMeta;tags:TagDefinition[];canEdit:boolean;canApprove:boolean;userRole:'admin'|'editor'|'reader';userId:string;userName:string;onClose:()=>void;onSaved:(meta:DocumentMeta,tags?:TagDefinition[])=>void;onRefresh:()=>void};
export default function DetailsPanel(p:Props){
  const [draft,setDraft]=useState(p.meta),[tagName,setTagName]=useState(''),[editingTag,setEditingTag]=useState<string>(),[tagDraft,setTagDraft]=useState({name:'',color:'#71806a'});
  const [comment,setComment]=useState(''),[editingComment,setEditingComment]=useState<string>(),[commentDraft,setCommentDraft]=useState(''),[comments,setComments]=useState<FileComment[]>([]);
  const [versions,setVersions]=useState<FileVersion[]>([]),[approvals,setApprovals]=useState<FileApproval[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [comparison,setComparison]=useState<{label:string;oldText:string;currentText:string}|null>(null);
  useEffect(()=>{loadComments(p.repo,p.department,p.scope,p.entry.path).then(setComments).catch(()=>setComments([]));loadVersions(p.repo,p.department,p.entry.path).then(setVersions).catch(()=>setVersions([]));loadApprovals(p.repo,p.department,p.entry.path).then(setApprovals).catch(()=>setApprovals([]));},[p.entry.path]);
  async function save(){setBusy(true);setError('');try{p.onSaved(await saveDocumentMeta(p.repo,p.department,p.scope,p.entry.path,draft));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function addTag(){if(!tagName.trim())return;setBusy(true);try{const tags=await createDocumentTag(p.repo,p.department,p.scope,tagName),created=tags.find(tag=>tag.name.toLowerCase()===tagName.trim().toLowerCase()),next=created&&!draft.tags.includes(created.id)?{...draft,tags:[...draft.tags,created.id]}:draft;setDraft(next);p.onSaved(next,tags);setTagName('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function saveTag(id:string){setBusy(true);try{const tags=await updateDocumentTag(p.repo,p.department,p.scope,id,tagDraft.name,tagDraft.color),available=new Set(tags.map(tag=>tag.id)),renamed=tags.find(tag=>tag.name.toLowerCase()===tagDraft.name.trim().toLowerCase()),next={...draft,tags:[...new Set(draft.tags.map(value=>value===id&&renamed?renamed.id:value).filter(value=>available.has(value)))]};setDraft(next);p.onSaved(next,tags);setEditingTag(undefined);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function removeTag(id:string){setBusy(true);try{const tags=await deleteDocumentTag(p.repo,p.department,p.scope,id),next={...draft,tags:draft.tags.filter(value=>value!==id)};setDraft(next);p.onSaved(next,tags);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function postComment(){if(!comment.trim())return;setBusy(true);try{const created=await addComment(p.repo,p.department,p.scope,p.entry.path,comment,p.userName);setComments(items=>[...items,created]);setComment('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function changeComment(item:FileComment,change:{text?:string;resolved?:boolean}){setBusy(true);try{const updated=await updateComment(p.repo,p.scope,p.entry.path,item.id,change);setComments(items=>items.map(value=>value.id===item.id?updated:value));setEditingComment(undefined);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function removeComment(item:FileComment){setBusy(true);try{await deleteComment(p.repo,p.scope,p.entry.path,item.id);setComments(items=>items.filter(value=>value.id!==item.id));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function submitApproval(){setBusy(true);try{const created=await requestApproval(p.department,p.entry.path);setApprovals(items=>[...items,created]);const next={...draft,status:'in_review' as const};setDraft(next);p.onSaved(next);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function decideApproval(item:FileApproval,status:'approved'|'rejected'){setBusy(true);try{const updated=await reviewApproval(item.id,status);setApprovals(items=>items.map(value=>value.id===item.id?updated:value));const next={...draft,status:status==='approved'?'approved' as const:'draft' as const};setDraft(next);p.onSaved(next);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function extractText(){setBusy(true);try{const next=await runOcr(p.department,p.entry.path);setDraft(next);p.onSaved(next);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function compareVersion(item:FileVersion){setBusy(true);setError('');try{const [oldFile,currentFile]=await Promise.all([readVersion(item.id),p.repo.read(p.entry.path)]);const [oldText,currentText]=await Promise.all([oldFile.text(),currentFile.text()]);setComparison({label:new Date(item.createdAt).toLocaleString(),oldText,currentText});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const canChangeComment=(item:FileComment)=>p.canApprove||!item.userId||item.userId===p.userId;
  return <div className="modal-backdrop" onClick={p.onClose}><section className="details-panel" role="dialog" aria-modal="true" aria-label={`Details for ${p.entry.name}`} onClick={e=>e.stopPropagation()}>
    <header><div><strong>{p.entry.name}</strong><span>{p.department} · {p.entry.kind}</span></div><button className="icon-button" aria-label="Close details" onClick={p.onClose}><X size={18}/></button></header><div className="details-scroll">
    <section><h3><Tag size={15}/>Tags</h3><div className="tag-picker">{p.tags.map(tag=><button key={tag.id} className={draft.tags.includes(tag.id)?'active':''} style={{'--tag-color':tag.color} as React.CSSProperties} disabled={!p.canEdit} onClick={()=>setDraft(value=>({...value,tags:value.tags.includes(tag.id)?value.tags.filter(id=>id!==tag.id):[...value.tags,tag.id]}))}>{tag.name}</button>)}</div>{p.canEdit&&<div className="inline-add"><input value={tagName} onChange={e=>setTagName(e.target.value)} placeholder="New tag"/><button className="secondary-button" onClick={()=>void addTag()}><Plus size={13}/>Add</button></div>}{p.canApprove&&<><div className="tag-admin">{p.tags.map(tag=>editingTag===tag.id?<div key={tag.id}><input value={tagDraft.name} onChange={e=>setTagDraft(v=>({...v,name:e.target.value}))}/><input aria-label="Tag color" type="color" value={tagDraft.color} onChange={e=>setTagDraft(v=>({...v,color:e.target.value}))}/><button onClick={()=>void saveTag(tag.id)}>Save</button><button className="danger" onClick={()=>void removeTag(tag.id)}><Trash2 size={13}/></button></div>:<button key={tag.id} onClick={()=>{setEditingTag(tag.id);setTagDraft({name:tag.name,color:tag.color});}}><span style={{background:tag.color}}/><Pencil size={12}/>{tag.name}</button>)}</div>{p.tags.length>1&&<p className="muted-note">Rename a tag to an existing tag name to merge them.</p>}</>}</section>
    <section><h3>Document information</h3><label>Description<textarea disabled={!p.canEdit} value={draft.description} onChange={e=>setDraft(v=>({...v,description:e.target.value}))}/></label><label>Status<select disabled={!p.canEdit} value={draft.status} onChange={e=>setDraft(v=>({...v,status:e.target.value as DocumentMeta['status']}))}><option value="draft">Draft</option><option value="in_review">In review</option><option value="approved">Approved</option><option value="superseded">Superseded</option><option value="archived">Archived</option></select></label><label>Review date<input disabled={!p.canEdit} type="date" value={draft.reviewDate||''} onChange={e=>setDraft(v=>({...v,reviewDate:e.target.value}))}/></label>{p.canEdit&&<button className="primary-button" disabled={busy} onClick={()=>void save()}>Save details</button>}{p.canEdit&&isServerRepository(p.repo)&&/\.(pdf|png|jpe?g|tiff?|bmp|webp)$/i.test(p.entry.name)&&<button className="secondary-button ocr-button" disabled={busy} onClick={()=>void extractText()}><ScanText size={14}/>{draft.ocrText?'Refresh searchable text':'Extract searchable text'}</button>}{draft.ocrText&&<p className="muted-note">OCR index: {draft.ocrText.length.toLocaleString()} characters</p>}</section>
    <section><h3><Send size={15}/>Approval</h3>{approvals.map(item=>{const stage=item.stages?.[item.currentStage||0],canReview=item.status==='pending'&&(p.userRole==='admin'||stage?.role===p.userRole);return <article className="approval-row" key={item.id}><div><strong>{item.status==='pending'&&stage?stage.name:item.status}</strong><span>Requested by {item.requestedByName} · {new Date(item.requestedAt).toLocaleString()}{item.dueAt?` · Due ${new Date(item.dueAt).toLocaleDateString()}`:''}</span></div>{canReview&&<span><button className="secondary-button" onClick={()=>void decideApproval(item,'rejected')}>Reject</button><button className="primary-button" onClick={()=>void decideApproval(item,'approved')}><Check size={13}/>Approve</button></span>}</article>})}{p.canEdit&&!approvals.some(item=>item.status==='pending')&&<button className="secondary-button" onClick={()=>void submitApproval()}><Send size={13}/>Request approval</button>}</section>
    <section><h3><MessageSquare size={15}/>Comments</h3><div className="comment-list">{comments.map(item=><article key={item.id} className={item.resolved?'resolved':''}><strong>{item.userName}</strong><time>{new Date(item.createdAt).toLocaleString()}{item.editedAt?' · edited':''}</time>{editingComment===item.id?<div className="comment-editor"><textarea value={commentDraft} onChange={e=>setCommentDraft(e.target.value)}/><button onClick={()=>void changeComment(item,{text:commentDraft})}>Save</button><button onClick={()=>setEditingComment(undefined)}>Cancel</button></div>:<p>{item.text}</p>}{canChangeComment(item)&&<div className="comment-actions"><button onClick={()=>void changeComment(item,{resolved:!item.resolved})}>{item.resolved?'Reopen':'Resolve'}</button><button onClick={()=>{setEditingComment(item.id);setCommentDraft(item.text);}}><Pencil size={12}/>Edit</button><button className="danger" onClick={()=>void removeComment(item)}><Trash2 size={12}/>Delete</button></div>}</article>)}{!comments.length&&<span>No comments yet.</span>}</div><div className="inline-add"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a comment or mention @name"/><button className="secondary-button" onClick={()=>void postComment()}>Post</button></div></section>
    <section><h3><History size={15}/>Version history</h3>{versions.length?<div className="version-list">{versions.map(item=><div key={item.id}><span><strong>{new Date(item.createdAt).toLocaleString()}</strong><small>{item.createdByName} · {item.reason}</small></span><span className="version-actions">{/\.(txt|md|csv|tsv|json|xml|ya?ml|log|html?|css|js|jsx|ts|tsx)$/i.test(p.entry.name)&&<button className="icon-button" title="Compare with current file" onClick={()=>void compareVersion(item)}><Columns2 size={14}/></button>}<button className="icon-button" title="Download version" onClick={()=>void downloadVersion(item.id,p.entry.name)}><Download size={14}/></button>{p.canEdit&&<button className="icon-button" title="Restore version" onClick={async()=>{await restoreVersion(item.id);p.onRefresh();}}><RotateCcw size={14}/></button>}{p.canApprove&&<button className="icon-button danger" title="Delete version" onClick={async()=>{await deleteVersion(item.id);setVersions(v=>v.filter(x=>x.id!==item.id));}}><Trash2 size={14}/></button>}</span></div>)}</div>:<p className="muted-note"><Clock3 size={13}/>Earlier versions appear after a server-stored file is edited.</p>}</section>
    {comparison&&<section className="version-compare"><h3><Columns2 size={15}/>Compare versions</h3><div><article><strong>Saved · {comparison.label}</strong><pre>{comparison.oldText}</pre></article><article><strong>Current</strong><pre>{comparison.currentText}</pre></article></div><button className="secondary-button" onClick={()=>setComparison(null)}>Close comparison</button></section>}
    {error&&<p className="inline-error">{error}</p>}</div></section></div>;
}
