import { ArrowDownWideNarrow, Plus, Star, FileSearch, Upload, FolderOpen } from 'lucide-react';
import FileIcon from './FileIcon';
import { formatSize, type Entry } from '../types';
import type { DragEvent, MouseEvent } from 'react';
interface Props { entries: Entry[]; selected?: string; selection:string[]; title: string; favorites: string[]; tags?:Record<string,Array<{name:string;color:string}>>; editable: boolean; onSelect: (e: Entry) => void; onToggle:(e:Entry)=>void; onOpen: (e: Entry) => void; onContext: (e: MouseEvent, file: Entry) => void; onAdd: (e: MouseEvent) => void; onDrop: (e: DragEvent) => void; sort: boolean; onSort: () => void; searching: boolean; }
export default function FilePanel(p: Props) {
  return <section className="file-panel" onDragOver={e => {if(p.editable)e.preventDefault();}} onDrop={p.editable?p.onDrop:undefined}><div className="panel-heading"><h1>Files</h1>{p.editable&&<button className="icon-button" aria-label="Add files or folders" onClick={p.onAdd}><Plus size={19}/></button>}</div>
    <div className="list-subheading"><span title={p.title}>{p.title}</span><button className="icon-button" aria-label={p.sort ? 'Sort A to Z' : 'Sort by latest'} title={p.sort ? 'Sort A to Z' : 'Sort by latest'} onClick={p.onSort}><ArrowDownWideNarrow size={15}/></button></div>
    <div className="file-list" role="listbox" aria-label="Files">{p.entries.map(entry => <button key={entry.path} role="option" aria-selected={p.selected === entry.path||p.selection.includes(entry.path)} className={`file-row ${p.selected === entry.path||p.selection.includes(entry.path) ? 'selected' : ''}`} onClick={event => event.ctrlKey||event.metaKey?p.onToggle(entry):p.onSelect(entry)} onDoubleClick={() => p.onOpen(entry)} onContextMenu={e => p.onContext(e,entry)} draggable={p.editable} onDragStart={e => { if(!p.editable)return;e.dataTransfer.setData('application/folio',entry.path); e.dataTransfer.effectAllowed = 'move'; }}>{entry.kind === 'folder' ? <FolderOpen className="list-folder-icon" size={26}/> : <FileIcon name={entry.name}/>}<span className="file-info"><strong title={entry.name}>{entry.kind === 'folder' ? entry.name : entry.name.replace(/\.[^.]+$/,'')}</strong><span>{entry.kind === 'folder' ? 'Folder' : <>{entry.name.split('.').pop()?.toUpperCase()}<i/> {formatSize(entry.size)}</>}</span>{p.tags?.[entry.path]?.length?<span className="file-tags">{p.tags[entry.path].slice(0,2).map(tag=><small key={tag.name} style={{'--tag-color':tag.color} as React.CSSProperties}>{tag.name}</small>)}</span>:null}</span>{p.favorites.includes(entry.path) && <Star className="row-star" size={12} fill="currentColor"/>}</button>)}</div>
    {!p.entries.length && <div className="list-empty">{p.searching ? <FileSearch size={30}/> : <FolderOpen size={30}/>}<strong>{p.searching ? 'Nothing found' : 'Room for something new'}</strong><span>{p.searching ? 'Try another name or file type.' : 'Drop files here, or use + to add them.'}</span></div>}
    <div className="file-footer"><span>{p.selection.length?`${p.selection.length} selected`:`${p.entries.length} ${p.entries.length === 1 ? 'item' : 'items'}`}</span>{p.editable&&<span><Upload size={12}/> Ctrl-click to select</span>}</div>
  </section>;
}
