import {useEffect,useRef,useState} from 'react';
import {X,Download,Save,LoaderCircle} from 'lucide-react';
import type {Entry,Repository} from '../types';
const endpoint=window.location.hostname==='tauri.localhost'?'http://localhost:1421':'/bridge';
const documentServer='https://office.getunio.dev';
const headers={'X-Folio-Request':'editor'};
type EditorInstance={destroyEditor():void};
type Session={id:string;config:Record<string,unknown>};
declare global { interface Window {DocsAPI?:{DocEditor:new(id:string,config:Record<string,unknown>)=>EditorInstance};} }
async function request(path:string,options:RequestInit={}){const response=await fetch(endpoint+path,{...options,headers:{...headers,...options.headers}});const result=await response.json();if(!response.ok)throw Error(result.error||'The local editor is unavailable.');return result;}
async function digest(blob:Blob){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))).map(x=>x.toString(16).padStart(2,'0')).join('');}
let scriptPromise:Promise<void>|undefined;
function loadEditor(){if(window.DocsAPI)return Promise.resolve();return scriptPromise ||= new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=documentServer+'/web-apps/apps/api/documents/api.js';script.onload=()=>resolve();script.onerror=()=>{scriptPromise=undefined;script.remove();reject(Error('ONLYOFFICE is unavailable.'));};document.head.appendChild(script);});}
export default function OfficeEditor({entry,repo,theme,onClose,onSaved}:{entry:Entry;repo:Repository;theme:'light'|'dark';onClose:()=>void;onSaved:()=>void}){
  const [message,setMessage]=useState('Connecting to ONLYOFFICE…');const [error,setError]=useState('');const [ready,setReady]=useState(false);const [working,setWorking]=useState(false);
  const session=useRef<Session | undefined>(undefined);const editor=useRef<EditorInstance | undefined>(undefined);const applied=useRef(0);const expected=useRef('');const dirty=useRef(false);const alive=useRef(true);const syncing=useRef(false);
  async function sync(){if(!session.current||syncing.current)return;syncing.current=true;try{const state=await request('/status/'+session.current.id);if(state.revision>applied.current){const response=await fetch(endpoint+'/saved/'+session.current.id);if(!response.ok)throw Error('Unable to retrieve the saved document.');const blob=await response.blob();const current=await repo.read(entry.path);if(await digest(current)!==expected.current)throw Error('The original changed outside this editor. Download the edited copy to preserve both versions.');if(!repo.replace)throw Error('This repository cannot save edits yet. Download the edited copy.');await repo.replace(entry.path,blob);expected.current=await digest(blob);applied.current=state.revision;dirty.current=false;if(alive.current){setMessage('Saved to '+entry.name);setError('');}onSaved();}}catch(e){if(alive.current)setError((e as Error).message);}finally{syncing.current=false;}}
  useEffect(()=>{let cancelled=false;alive.current=true;let timer:ReturnType<typeof setInterval>|undefined;
    (async()=>{const health=await request('/health');if(!health.ready)throw Error('ONLYOFFICE is starting. Wait a moment and reopen the editor.');const blob=await repo.read(entry.path);expected.current=await digest(blob);const created:Session=await request('/sessions',{method:'POST',headers:{'X-Folio-Name':encodeURIComponent(entry.name),'Content-Type':'application/octet-stream'},body:blob});if(cancelled)return;session.current=created;await loadEditor();if(cancelled)return;const editorConfig=created.config.editorConfig as Record<string,unknown>|undefined;const customization=(editorConfig?.customization as Record<string,unknown>|undefined)||{};const themedConfig={...created.config,editorConfig:{...editorConfig,customization:{...customization,uiTheme:theme==='dark'?'theme-dark':'theme-light'}}};editor.current=new window.DocsAPI!.DocEditor('folio-office-editor',{...themedConfig,events:{onAppReady:()=>{if(!cancelled){setReady(true);setMessage(`Editing locally · ${theme==='dark'?'Dark':'Light'} editor theme · Save writes changes back to Folio`);}},onDocumentStateChange:(event:{data:boolean})=>{if(event.data){dirty.current=true;setMessage('Unsaved changes · use Save when ready');}},onError:(event:{data?:{errorDescription?:string}})=>setError(event.data?.errorDescription||'The document editor reported an error.')}});timer=setInterval(()=>void sync(),2000);
    })().catch(e=>{if(!cancelled)setError((e as Error).message+' Check that the editor service is running.');});
    const beforeUnload=(event:BeforeUnloadEvent)=>{if(dirty.current){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',beforeUnload);
    return()=>{cancelled=true;alive.current=false;clearInterval(timer);window.removeEventListener('beforeunload',beforeUnload);editor.current?.destroyEditor();};
  },[]);
  async function save(close=false){if(!session.current)return;setWorking(true);setError('');try{const baseline=applied.current;const result=await request('/save/'+session.current.id,{method:'POST'});if(result.error && result.error!==4)throw Error('ONLYOFFICE could not save yet. Try again shortly.');if(result.error===4){if(dirty.current)throw Error('Changes are still reaching the server. Wait a moment and save again.');await sync();if(close)onClose();return;}setMessage('Saving changes to Folio…');for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,1000));await sync();if(applied.current>baseline){if(close)onClose();return;}}throw Error('Saving is taking longer than expected. Keep the editor open and retry.');}catch(e){setError((e as Error).message);}finally{setWorking(false);}}
  async function download(){if(!session.current)return;const response=await fetch(endpoint+'/saved/'+session.current.id);const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=entry.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
  return <div className="office-overlay" role="dialog" aria-modal="true" aria-label={'Edit '+entry.name}><header className="office-header"><strong>{entry.name}</strong><span role="status">{message}</span><button className="secondary-button" disabled={!ready||working} onClick={()=>void download()}><Download size={15}/>Download saved copy</button><button className="primary-button" disabled={!ready||working} onClick={()=>void save()}><Save size={15}/>{working?'Saving…':'Save'}</button><button className="icon-button" aria-label="Save and close editor" disabled={working} onClick={()=>dirty.current?void save(true):onClose()}><X size={20}/></button></header>{error&&<div className="office-error" role="alert">{error}</div>}<div className="office-body">{!ready&&!error&&<div className="office-loading"><LoaderCircle className="spinner"/>Starting editor…</div>}<div id="folio-office-editor"/></div></div>;
}
