import {useState} from 'react';
import {ArrowUpRight,HardDrive,Moon,Plus,Settings2,Sun,Trash2,UserRound,X} from 'lucide-react';
import {changePassword,makeUser,type FolioUser,type UserRole} from '../services/auth';
import type {DocumentTemplate,TemplateKind} from '../services/templates';
import type {Repository} from '../types';
import TemplateSettings from './TemplateSettings';
import ApprovalSettings from './ApprovalSettings';

type Tab='account'|'appearance'|'configuration';
type Props={currentUser:FolioUser;users:FolioUser[];departments:string[];templates:DocumentTemplate[];initialTab?:Tab;theme:'light'|'dark';notifications:boolean;editor:string;repo:Repository|null;native:boolean;onClose:()=>void;onTheme:(value:'light'|'dark')=>void;onNotifications:(enabled:boolean)=>Promise<void>;onEditor:(value:string)=>void;onConnect:()=>void;onImportBrowserData?:()=>Promise<string>;onLogout:()=>void;onUsers:(users:FolioUser[])=>void;onSaveUser?:(input:{name:string;email:string;password?:string;role:UserRole;departments:string[]},id?:string)=>Promise<void>;onRemoveUser?:(id:string)=>Promise<void>;onAddDepartment:(name:string)=>boolean|Promise<boolean>;onRenameDepartment:(from:string,to:string)=>Promise<boolean>;onRemoveDepartment:(name:string)=>Promise<boolean>;onCreateTemplate:(name:string,kind:TemplateKind)=>Promise<void>;onUploadTemplates:(files:File[])=>Promise<void>;onEditTemplate:(template:DocumentTemplate)=>void;onRemoveTemplate:(id:string)=>Promise<void>};

export default function SettingsPanel(p:Props){
  const [tab,setTab]=useState<Tab>(p.initialTab||'account');
  const [adding,setAdding]=useState(false);const [editing,setEditing]=useState<string>();
  const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [role,setRole]=useState<UserRole>('reader');const [access,setAccess]=useState<string[]>([]);const [error,setError]=useState('');
  const [departmentName,setDepartmentName]=useState('');const [departmentDrafts,setDepartmentDrafts]=useState<Record<string,string>>({});
  const admin=p.currentUser.role==='admin';

  function resetUser(){setAdding(false);setEditing(undefined);setName('');setEmail('');setPassword('');setRole('reader');setAccess([]);setError('');}
  function editUser(user:FolioUser){setAdding(true);setEditing(user.id);setName(user.name);setEmail(user.email);setPassword('');setRole(user.role);setAccess(user.departments);setError('');}
  async function saveUser(){try{setError('');if(!name.trim()||!email.trim())throw Error('Name and email are required.');if((!editing||password)&&password.length<8)throw Error('New passwords need at least 8 characters.');if(p.users.some(user=>user.id!==editing&&user.email===email.trim().toLowerCase()))throw Error('That email is already in use.');const original=editing?p.users.find(user=>user.id===editing):undefined;if(original?.role==='admin'&&role!=='admin'&&p.users.filter(user=>user.role==='admin').length===1)throw Error('Keep at least one administrator account.');if(p.onSaveUser){await p.onSaveUser({name:name.trim(),email:email.trim().toLowerCase(),password:password||undefined,role,departments:access},editing);resetUser();return;}let next:FolioUser;if(original){next={...original,name:name.trim(),email:email.trim().toLowerCase(),role,departments:access};if(password)next=await changePassword(next,password);}else next=await makeUser({name,email,password,role,departments:access});p.onUsers(editing?p.users.map(user=>user.id===editing?next:user):[...p.users,next]);resetUser();}catch(reason){setError((reason as Error).message);}}
  async function removeUser(user:FolioUser){if(user.id===p.currentUser.id){setError('The signed-in administrator cannot remove their own account.');return;}try{if(p.onRemoveUser)await p.onRemoveUser(user.id);else p.onUsers(p.users.filter(item=>item.id!==user.id));}catch(reason){setError((reason as Error).message);}}
  function toggleDepartment(value:string){setAccess(items=>items.includes(value)?items.filter(item=>item!==value):[...items,value]);}

  return <div className="modal-backdrop" onClick={p.onClose}><section className="settings-shell" role="dialog" aria-modal="true" aria-labelledby="settings-title" onClick={event=>event.stopPropagation()}>
    <aside className="settings-nav"><div className="settings-brand"><Settings2 size={18}/><strong id="settings-title">Settings</strong></div><button className={tab==='account'?'active':''} onClick={()=>setTab('account')}><UserRound size={16}/>Account</button><button className={tab==='appearance'?'active':''} onClick={()=>setTab('appearance')}><Sun size={16}/>Appearance</button><button className={tab==='configuration'?'active':''} onClick={()=>setTab('configuration')}><Settings2 size={16}/>Configuration</button><div className="settings-user"><strong>{p.currentUser.name}</strong><span>{p.currentUser.role}</span></div></aside>
    <div className="settings-content"><button className="settings-close icon-button" aria-label="Close settings" onClick={p.onClose}><X size={19}/></button>
      {tab==='account'&&<><div className="settings-title"><h2>Account</h2><p>{admin?'Manage people, roles, and department access.':'Your Folio account and access.'}</p></div><div className="account-summary"><span className="account-avatar">{p.currentUser.name.slice(0,1).toUpperCase()}</span><div><strong>{p.currentUser.name}</strong><span>{p.currentUser.email} · {p.currentUser.role}</span></div><button className="secondary-button" onClick={p.onLogout}>Sign out</button></div>{admin&&<><div className="section-heading"><div><h3>Users</h3><p>Administrators control accounts. Editors can change documents. Readers have view-only access.</p></div><button className="primary-button" onClick={()=>{resetUser();setAdding(true);}}><Plus size={14}/>Add user</button></div><div className="user-list">{p.users.map(user=><div className="user-row" key={user.id}><span className="account-avatar small">{user.name.slice(0,1).toUpperCase()}</span><div><strong>{user.name}{user.id===p.currentUser.id?' (you)':''}</strong><span>{user.email}</span><small>{user.role==='admin'?'All departments':user.departments.length?user.departments.join(', '):'No department access'}</small></div><span className={`role-badge role-${user.role}`}>{user.role}</span><button className="secondary-button" onClick={()=>editUser(user)}>Configure</button><button className="icon-button danger" aria-label={`Remove ${user.name}`} onClick={()=>removeUser(user)}><Trash2 size={15}/></button></div>)}</div>{adding&&<div className="user-editor"><h3>{editing?'Configure user':'Add a user'}</h3><div className="form-grid"><label>Name<input value={name} onChange={event=>setName(event.target.value)}/></label><label>Email<input type="email" value={email} onChange={event=>setEmail(event.target.value)}/></label><label>{editing?'New password (optional)':'Password'}<input type="password" value={password} onChange={event=>setPassword(event.target.value)} placeholder={editing?'Leave blank to keep current password':'At least 8 characters'}/></label><label>Role<select value={role} onChange={event=>setRole(event.target.value as UserRole)}><option value="admin">Administrator</option><option value="editor">Editor</option><option value="reader">Reader</option></select></label></div><label>Department access</label><div className="access-grid">{p.departments.map(item=><label key={item}><input type="checkbox" checked={role==='admin'||access.includes(item)} disabled={role==='admin'} onChange={()=>toggleDepartment(item)}/>{item}</label>)}</div>{error&&<p className="inline-error">{error}</p>}<div className="dialog-actions"><button className="secondary-button" onClick={resetUser}>Cancel</button><button className="primary-button" onClick={()=>void saveUser()}>Save user</button></div></div>}</>}</>}
      {tab==='appearance'&&<><div className="settings-title"><h2>Appearance</h2><p>Choose how Folio looks and notifies you on this device.</p></div><div className="settings-section"><label>Theme</label><div className="theme-switch" role="group" aria-label="Appearance"><button className={p.theme==='light'?'active':''} onClick={()=>p.onTheme('light')}><Sun size={15}/>Light</button><button className={p.theme==='dark'?'active':''} onClick={()=>p.onTheme('dark')}><Moon size={15}/>Dark</button></div><label>Desktop notifications</label><div className="theme-switch"><button className={!p.notifications?'active':''} onClick={()=>void p.onNotifications(false)}>Off</button><button className={p.notifications?'active':''} onClick={()=>void p.onNotifications(true)}>On</button></div></div></>}
      {tab==='configuration'&&<><div className="settings-title"><h2>Configuration</h2><p>Manage departments, templates, storage, and document behavior.</p></div>{admin&&<><div className="settings-section"><div className="section-heading"><div><h3>Departments</h3><p>Every department keeps an independent set of folders and files.</p></div></div><div className="department-settings">{p.departments.map(item=><div className="department-setting-row" key={item}><input value={departmentDrafts[item]??item} onChange={event=>setDepartmentDrafts(values=>({...values,[item]:event.target.value}))}/><button className="secondary-button" onClick={async()=>{const next=(departmentDrafts[item]??item).trim();if(await p.onRenameDepartment(item,next))setDepartmentDrafts({});}}>Save</button><button className="icon-button danger" aria-label={`Remove ${item}`} onClick={()=>void p.onRemoveDepartment(item)}><Trash2 size={15}/></button></div>)}<div className="department-setting-row"><input placeholder="New department" value={departmentName} onChange={event=>setDepartmentName(event.target.value)}/><button className="secondary-button" onClick={async()=>{if(await p.onAddDepartment(departmentName))setDepartmentName('');}}>Add</button></div></div></div>{p.repo?.storageKey?.startsWith('server:')&&<ApprovalSettings departments={p.departments}/>}<TemplateSettings templates={p.templates} onCreate={p.onCreateTemplate} onUpload={p.onUploadTemplates} onEdit={p.onEditTemplate} onRemove={p.onRemoveTemplate}/></>}<div className="settings-section"><label>Document repository</label><div className="setting-box"><HardDrive size={21}/><div><strong>{p.repo?.storageKey?.startsWith('server:')?'Shared server workspace':p.repo?.mode==='demo'?'Browser workspace':p.repo?.label}</strong><span>{p.repo?.storageKey?.startsWith('server:')?'Files and permissions are stored by this Folio server.':p.repo?.mode==='demo'?'Files and folders are saved in this browser.':p.native?'Documents are stored in ~/Folio.':'Reconnect this folder after refreshing the browser.'}</span></div></div>{admin&&!p.repo?.storageKey?.startsWith('server:')&&<button className="secondary-button" onClick={p.onConnect}>{p.native?'Refresh repository':'Connect a local folder'}<ArrowUpRight size={15}/></button>}{admin&&p.onImportBrowserData&&<button className="secondary-button" onClick={async()=>{try{setError(await p.onImportBrowserData!());}catch(reason){setError((reason as Error).message);}}}>Import browser workspaces</button>}<label htmlFor="editor">Preferred editor</label><select id="editor" value={p.editor} onChange={event=>p.onEditor(event.target.value)}><option value="system">System default</option><option value="onlyoffice">ONLYOFFICE</option></select></div></>}
    </div>
  </section></div>;
}
