import {useEffect,useState} from 'react';
import {Activity,ArchiveRestore,FileClock,LayoutDashboard,RotateCcw,Search,Tags,Trash2,X} from 'lucide-react';
import {deleteTrash,loadActivity,loadNotifications,loadTrash,readNotification,restoreTrash,type DocumentData,type SavedView} from '../services/documentData';
import type {Entry} from '../types';
type ActivityItem={id:string;userName:string;action:string;department?:string;path?:string;at:number};
type TrashItem={id:string;department:string;path:string;kind:string;deletedAt:number;deletedByName:string};
type NotificationItem={id:string;message:string;department:string;path:string;createdAt:number;read:boolean};
type Props={entries:Entry[];data:DocumentData;serverMode:boolean;canPurge:boolean;onClose:()=>void;onApplyView:(query:string)=>void;onOpen:(department:string,path:string)=>void;onRemoveView:(id:string)=>void;onRestored:()=>void};
const actionLabel=(value:string)=>value.replaceAll('.',' ').replace(/^\w/,letter=>letter.toUpperCase());
export default function WorkspaceCenter(p:Props){
  const [tab,setTab]=useState<'overview'|'activity'|'trash'>('overview'),[activity,setActivity]=useState<ActivityItem[]>([]),[trash,setTrash]=useState<TrashItem[]>([]),[notifications,setNotifications]=useState<NotificationItem[]>([]),[error,setError]=useState('');
  useEffect(()=>{if(!p.serverMode)return;loadActivity().then(setActivity).catch(e=>setError((e as Error).message));loadTrash().then(setTrash).catch(e=>setError((e as Error).message));loadNotifications().then(setNotifications).catch(e=>setError((e as Error).message));},[p.serverMode]);
  const metadata=Object.values(p.data.metadata),due=Object.entries(p.data.metadata).filter(([,meta])=>meta.reviewDate&&new Date(meta.reviewDate).getTime()<=Date.now()+30*86400000),review=metadata.filter(meta=>meta.status==='in_review').length;
  async function restore(item:TrashItem){try{await restoreTrash(item.id);setTrash(items=>items.filter(value=>value.id!==item.id));p.onRestored();}catch(e){setError((e as Error).message);}}
  async function purge(item:TrashItem){try{await deleteTrash(item.id);setTrash(items=>items.filter(value=>value.id!==item.id));}catch(e){setError((e as Error).message);}}
  return <div className="modal-backdrop" onClick={p.onClose}><section className="workspace-center" role="dialog" aria-modal="true" aria-label="Workspace center" onClick={e=>e.stopPropagation()}>
    <header><div><LayoutDashboard size={19}/><strong>Workspace center</strong></div><button className="icon-button" aria-label="Close workspace center" onClick={p.onClose}><X size={18}/></button></header>
    <nav><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><LayoutDashboard size={15}/>Overview</button><button className={tab==='activity'?'active':''} onClick={()=>setTab('activity')}><Activity size={15}/>Activity</button><button className={tab==='trash'?'active':''} onClick={()=>setTab('trash')}><ArchiveRestore size={15}/>Recycle bin</button></nav>
    <div className="center-content">{tab==='overview'&&<><div className="metric-grid"><article><FileClock/><strong>{p.entries.filter(e=>e.kind==='file').length}</strong><span>Documents</span></article><article><Tags/><strong>{p.data.tags.length}</strong><span>Tags</span></article><article><Activity/><strong>{review}</strong><span>In review</span></article><article><FileClock/><strong>{due.length}</strong><span>Review soon</span></article></div>
      <section><h3>Saved searches</h3>{p.data.savedViews.length?<div className="saved-views">{p.data.savedViews.map((view:SavedView)=><div key={view.id}><button onClick={()=>p.onApplyView(view.query)}><Search size={14}/><span><strong>{view.name}</strong><small>{view.query}</small></span></button><button className="icon-button" aria-label={`Remove ${view.name}`} onClick={()=>p.onRemoveView(view.id)}><X size={13}/></button></div>)}</div>:<p className="empty-note">Run a search and choose “Save this search” to keep it here.</p>}</section>
      <section><h3>Mentions</h3>{notifications.length?<div className="review-list">{notifications.slice(0,6).map(item=><button key={item.id} className={item.read?'':'unread'} onClick={async()=>{await readNotification(item.id);setNotifications(items=>items.map(value=>value.id===item.id?{...value,read:true}:value));p.onOpen(item.department,item.path);}}><strong>{item.message}</strong><span>{new Date(item.createdAt).toLocaleString()}</span></button>)}</div>:<p className="empty-note">No mentions yet. Use @name or @email in a comment.</p>}</section>
      <section><h3>Upcoming reviews</h3>{due.length?<div className="review-list">{due.slice(0,8).map(([path,meta])=><button key={path} onClick={()=>p.onOpen('',path)}><strong>{path}</strong><span>{new Date(meta.reviewDate!).toLocaleDateString()}</span></button>)}</div>:<p className="empty-note">No documents need review in the next 30 days.</p>}</section></>}
      {tab==='activity'&&<section><h3>Recent activity</h3>{p.serverMode?<div className="activity-list">{activity.map(item=><article key={item.id}><span className="activity-dot"/><div><strong>{item.userName} · {actionLabel(item.action)}</strong><span>{item.path||item.department||'Workspace'} · {new Date(item.at).toLocaleString()}</span></div></article>)}</div>:<p className="empty-note">Shared activity is available when Folio runs through the server.</p>}</section>}
      {tab==='trash'&&<section><h3>Recycle bin</h3>{p.serverMode?<div className="trash-list">{trash.map(item=><article key={item.id}><div><strong>{item.path}</strong><span>{item.department} · Deleted by {item.deletedByName} · {new Date(item.deletedAt).toLocaleString()}</span></div><span className="trash-actions"><button className="secondary-button" onClick={()=>void restore(item)}><RotateCcw size={13}/>Restore</button>{p.canPurge&&<button className="secondary-button danger" onClick={()=>void purge(item)}><Trash2 size={13}/>Delete permanently</button>}</span></article>)}{!trash.length&&<p className="empty-note">The recycle bin is empty.</p>}</div>:<p className="empty-note">Recoverable deletion is available when Folio runs through the server.</p>}</section>}
      {error&&<p className="inline-error">{error}</p>}
    </div>
  </section></div>;
}
